apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv01
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/local-pv01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv02
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/local-pv02"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv03
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/local-pv03"
